### PR TITLE
Update Simplified Chinese localization

### PR DESCRIPTION
**Pull request by Jerry23011**
### Changes
- Add the latest translations
- Updates for some previous ones.

### CODE REVIEW

**Comment by Jerry23011** [comment]
@NghiaTranUIT Hi, it's all done, there are still some inconsistencies with the localization like the toolbar options (please  see screenshot below), but I think those are for another day. Please tell me if there's anything that needs to be changed.
截屏2023-01-30 22 56 32

**Comment by Jerry23011** [comment]
@NghiaTranUIT Hi, it's all done, there are still some inconsistencies with the localization like the toolbar options (please see screenshot below), but I think those are for another day. Please tell me if there's anything that needs to be changed.
截屏2023-01-30 23 00 42

**Comment by NghiaTranUIT** [comment]
Thanks @Jerry23011 for your hard work. It's a huge update 🙇 

Just wondering: Did your PR branch off from my PR (https://github.com/ProxymanApp/proxyman-localization/pull/8) 🤔  ?

If yes, I can safely close my PR and merge your one to avoid conflicts.

**Comment by Jerry23011** [comment]
Yes, the branch I created was forked from your PR, and the merge target is the 4.1.0 branch, not the main branch :)

**Pull request merged**
